export default {
  pricing: {
    en: "/pricing",
    nl: "/prijzen",
    es: "/precios",
    de: "/preise",
    it: "/prezzi",
    fr: "/tarifs",
  },
  video: {
    en: "/video",
    nl: "/video",
    es: "/video",
    de: "/video",
    it: "/video",
    fr: "/video",
  },
  "blog/index": {
    en: "/blog",
    nl: "/blog",
    es: "/blog",
    de: "/blog",
    it: "/blog",
    fr: "/blog",
  },
  "blog/[slug]": {
    // params need to be put back here as you would with Nuxt Dynamic Routes
    // https://nuxt.com/docs/guide/directory-structure/pages#dynamic-routes
    en: "/blog/[slug]",
    nl: "/blog/[slug]",
    es: "/blog/[slug]",
    de: "/blog/[slug]",
    it: "/blog/[slug]",
    fr: "/blog/[slug]",
  },
  "press/index": {
    en: "/press",
    nl: "/pers",
    es: "/prensa",
    de: "/presse",
    it: "/stampa",
    fr: "/presse",
  },
  "glossary/index": {
    en: "/glossaries",
    nl: "/begrippenlijsten",
    es: "/glosarios",
    de: "/glossare",
    it: "/glossari",
    fr: "/glossaires",
  },
  "glossary/[category]/index": {
    en: "/glossary/[category]",
    nl: "/begrippenlijst/[category]",
    es: "/glosario/[category]",
    de: "/glossar/[category]",
    it: "/glossario/[category]",
    fr: "/glossaire/[category]",
  },
  "glossary/[category]/[slug]": {
    en: "/glossary/[category]/[slug]",
    nl: "/begrippenlijst/[category]/[slug]",
    es: "/glosario/[category]/[slug]",
    de: "/glossar/[category]/[slug]",
    it: "/glossario/[category]/[slug]",
    fr: "/glossaire/[category]/[slug]",
  },
  "glossary/[category]/key-terms/index": {
    en: "/glossary/[category]/key-terms",
    nl: "/begrippenlijst/[category]/kernbegrippen",
    es: "/glosario/[category]/terminos-clave",
    de: "/glossar/[category]/schlusselbegriffe",
    it: "/glossario/[category]/termini-chiave",
    fr: "/glossaire/[category]/termes-cles",
  },
  "glossary/[category]/key-terms/[slug]": {
    en: "/glossary/[category]/key-term/[slug]",
    nl: "/begrippenlijst/[category]/kernbegrip/[slug]",
    es: "/glosario/[category]/termino-clave/[slug]",
    de: "/glossar/[category]/schlusselbegriff/[slug]",
    it: "/glossario/[category]/termine-chiave/[slug]",
    fr: "/glossaire/[category]/terme-cle/[slug]",
  },
  "google-analytics-countries/index": {
    en: "/google-analytics-is-illegal-in-these-countries",
    nl: "/google-analytics-verboden-in-deze-landen",
    es: "/google-analytics-prohibido-en-estos-paises",
    de: "/google-analytics-in-diesen-landern-verboten",
    it: "/google-analytics-vietato-in-questi-paesi",
    fr: "/google-analytics-interdit-dans-ces-pays",
  },
  "google-analytics-countries/[slug]": {
    en: "/google-analytics-illegal/[slug]",
    nl: "/google-analytics-verboden/[slug]",
    es: "/google-analytics-paises/[slug]",
    de: "/google-analytics-lander/[slug]",
    it: "/google-analytics-paesi/[slug]",
    fr: "/google-analytics-pays/[slug]",
  },
  "resources/index": {
    en: "/resources",
    nl: "/bronnen",
    es: "/recursos",
    de: "/ressourcen",
    it: "/risorse",
    fr: "/ressources",
  },
  "resources/comparisons/index": {
    en: "/resources/comparisons",
    nl: "/bronnen/vergelijkingen",
    es: "/recursos/comparaciones",
    de: "/ressourcen/vergleiche",
    it: "/risorse/confronti",
    fr: "/ressources/comparaisons",
  },
  "resources/comparisons/[slug]": {
    en: "/resources/comparisons/[slug]",
    nl: "/bronnen/vergelijkingen/[slug]",
    es: "/recursos/comparaciones/[slug]",
    de: "/ressourcen/vergleiche/[slug]",
    it: "/risorse/confronti/[slug]",
    fr: "/ressources/comparaisons/[slug]",
  },
  "resources/analytics-review/index": {
    en: "/resources/analytics-review",
    nl: "/bronnen/analyse-beoordeling",
    es: "/recursos/revisiones-de-analiticas",
    de: "/ressourcen/analysebewertung",
    it: "/risorse/recensione-analitica",
    fr: "/ressources/avis-analytiques",
  },
  "resources/analytics-review/[slug]": {
    en: "/resources/analytics-review/[slug]",
    nl: "/bronnen/analyse-beoordeling/[slug]",
    es: "/recursos/revisiones-de-analiticas/[slug]",
    de: "/ressourcen/analysebewertung/[slug]",
    it: "/risorse/recensione-analitica/[slug]",
    fr: "/ressources/avis-analytiques/[slug]",
  },
  "resources/analytics-pricing/index": {
    en: "/resources/analytics-pricing",
    nl: "/bronnen/analyse-prijzen",
    es: "/recursos/precios-de-analiticas",
    de: "/ressourcen/analysepreise",
    it: "/risorse/prezzo-analitico",
    fr: "/ressources/prix-analytiques",
  },
  "resources/analytics-pricing/[slug]": {
    en: "/resources/analytics-pricing/[slug]",
    nl: "/bronnen/analyse-prijzen/[slug]",
    es: "/recursos/precios-de-analiticas/[slug]",
    de: "/ressourcen/analysepreise/[slug]",
    it: "/risorse/prezzo-analitico/[slug]",
    fr: "/ressources/prix-analytiques/[slug]",
  },
  "resources/alternatives/index": {
    en: "/resources/alternatives",
    nl: "/bronnen/alternatieven",
    es: "/recursos/alternativas",
    de: "/ressourcen/alternativen",
    it: "/risorse/alternative",
    fr: "/ressources/alternatives",
  },
  "resources/alternatives/[slug]": {
    en: "/resources/alternatives/[slug]",
    nl: "/bronnen/alternatieven/[slug]",
    es: "/recursos/alternativas/[slug]",
    de: "/ressourcen/alternativen/[slug]",
    it: "/risorse/alternative/[slug]",
    fr: "/ressources/alternatives/[slug]",
  },
  "utm-builder/index": {
    en: "/utm-builder",
    nl: "/utm-builder",
    es: "/constructor-de-utm",
    de: "/utm-generator",
    it: "/generatore-utm",
    fr: "/constructeur-utm",
  },
  "utm-builder/[slug]": {
    en: "/utm-builder/[slug]",
    nl: "/utm-builder/[slug]",
    es: "/constructor-de-utm/[slug]",
    de: "/utm-generator/[slug]",
    it: "/generatore-utm/[slug]",
    fr: "/constructeur-utm/[slug]",
  },
  "is-gdpr-compliant": {
    en: "/is-gdpr-compliant",
    nl: "/is-gdpr-compliant",
    es: "/es-conforme-gdpr",
    de: "/ist-gdpr-konform",
    it: "/e-conforme-gdpr",
    fr: "/est-conforme-gdpr",
  },
  "is-gdpr-compliant/[slug]": {
    en: "/is-gdpr-compliant/[slug]",
    nl: "/is-gdpr-compliant/[slug]",
    es: "/es-conforme-gdpr/[slug]",
    de: "/ist-gdpr-konform/[slug]",
    it: "/e-conforme-gdpr/[slug]",
    fr: "/est-conforme-gdpr/[slug]",
  },
  "case-studies/index": {
    en: "/case-studies",
    de: "/fallstudien",
    es: "/estudios-de-caso",
    fr: "/etudes-de-cas",
    it: "/studi-di-caso",
    nl: "/casestudies",
  },
  "case-studies/[slug]": {
    en: "/case-studies/[slug]",
    de: "/fallstudien/[slug]",
    es: "/estudios-de-caso/[slug]",
    fr: "/etudes-de-cas/[slug]",
    it: "/studi-di-caso/[slug]",
    nl: "/casestudies/[slug]",
  },
  "guides/index": {
    en: "/guides",
    de: "/anleitungen", // German: "Anleitungen" is suitable for tutorials or how-to guides.
    es: "/tutoriales", // Spanish: "Tutoriales" specifically refers to tutorials.
    fr: "/tutoriels", // French: "Tutoriels" is the direct translation for tutorials.
    it: "/guide-pratiche", // Italian: "Guide pratiche" can be used for practical guides or tutorials.
    nl: "/handleidingen", // Dutch: "Handleidingen" typically refers to manuals or detailed guides.
  },
  "guides/[slug]": {
    en: "/guides/[slug]",
    de: "/anleitungen/[slug]",
    es: "/tutoriales/[slug]",
    fr: "/tutoriels/[slug]",
    it: "/guide-pratiche/[slug]",
    nl: "/handleidingen/[slug]",
  },
} as const;
