export default {
  pricing: "/pricing",
  video: "/video",
  "blog/index": "/blog",
  "blog/[slug]": "/blog/[slug]",
  "press/index": "/press",
  "glossary/index": "/glossaries",
  "glossary/[category]/index": "/glossary/[category]",
  "glossary/[category]/[slug]": "/glossary/[category]/[slug]",
  "glossary/[category]/key-terms/index": "/glossary/[category]/key-terms",
  "glossary/[category]/key-terms/[slug]":
    "/glossary/[category]/key-term/[slug]",
  "google-analytics-countries/index":
    "/google-analytics-is-illegal-in-these-countries",
  "google-analytics-countries/[slug]": "/google-analytics-illegal/[slug]",
  "resources/index": "/resources",
  "resources/comparisons/index": "/resources/comparisons",
  "resources/comparisons/[slug]": "/resources/comparisons/[slug]",
  "resources/analytics-review/index": "/resources/analytics-review",
  "resources/analytics-review/[slug]": "/resources/analytics-review/[slug]",
  "resources/analytics-pricing/index": "/resources/analytics-pricing",
  "resources/analytics-pricing/[slug]": "/resources/analytics-pricing/[slug]",
  "resources/alternatives/index": "/resources/alternatives",
  "resources/alternatives/[slug]": "/resources/alternatives/[slug]",
  "utm-builder/index": "/utm-builder",
  "utm-builder/[slug]": "/utm-builder/[slug]",
  "is-gdpr-compliant/index": "/is-gdpr-compliant",
  "is-gdpr-compliant/[slug]": "/is-gdpr-compliant/[slug]",
  "case-studies/index": "/case-studies",
  "case-studies/[slug]": "/case-studies/[slug]",
  "guides/index": "/guides",
  "guides/[slug]": "/guides/[slug]",
} as const;
